[versions]
accompanistPermissions = "0.37.3"
agp = "8.13.0"
asms = "1.8.7.2"
baidumapsdk_location = "9.6.6.1"
baidumapsdk_map = "7.6.6"
barcodeScanning = "17.3.0"
base = "7.6.6"
cameraMlkitVisionVersion = "1.5.1"
coilCompose = "3.3.0"
common = "9.8.8"
core = "3.5.3"
datastore = "1.1.7"
fastjson2 = "2.0.60"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
kotlinxSerializationJson = "1.9.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.11.00"
material = "1.9.4"
material3 = "1.4.0"
navigationCompose = "2.9.6"
okhttp = "5.3.0"
patternlocker = "2.5.7"
protobufJavalite = "4.33.0"
reorderable = "3.0.0"
stackbricks = "2.4.2"

[libraries]

accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityCompose" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraMlkitVisionVersion" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "cameraMlkitVisionVersion" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraMlkitVisionVersion" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraMlkitVisionVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "material" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
asms = { module = "com.umeng.umsdk:asms", version.ref = "asms" }
baidumapsdk_location = { module = "com.baidu.lbsyun:BaiduMapSDK_Location", version.ref = "baidumapsdk_location" }
baidumapsdk_map = { module = "com.baidu.lbsyun:BaiduMapSDK_Map", version.ref = "baidumapsdk_map" }
baidumapsdk_search = { module = "com.baidu.lbsyun:BaiduMapSDK_Search", version.ref = "baidumapsdk_map" }
barcode-scanning = { module = "com.google.mlkit:barcode-scanning", version.ref = "barcodeScanning" }
camera-mlkit-vision = { module = "androidx.camera:camera-mlkit-vision", version.ref = "cameraMlkitVisionVersion" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilCompose" }
common = { module = "com.umeng.umsdk:common", version.ref = "common" }
core = { module = "com.google.zxing:core", version.ref = "core" }
fastjson2 = { module = "com.alibaba.fastjson2:fastjson2", version.ref = "fastjson2" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
lbsyun-base = { module = "com.baidu.lbsyun:base", version.ref = "base" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
patternlocker = { module = "com.github.ihsg:PatternLocker", version.ref = "patternlocker" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobufJavalite" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }
stackbricks = { module = "org.aquamarine5.brainspark:stackbricks", version.ref = "stackbricks" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

